(()=>{
const guides={
en:{summary:'App Guide & About',created:'CREATED FOR THE FELLOWSHIP',about:'A mobile golf companion created by Rick Kulon to bring fellowship, course guidance, scoring and group communication together in one simple app.',sections:[
['Before Your First Round',['Tap Sign Up and enter your first name, last name, email and phone number.','Confirm your account from the Supabase verification email, then return and sign in. Your login is remembered on that device.','Open My Account → My Profile & Picture to finish your profile.','Open My Clubs & Distances and save the distance you normally carry each club.']],
['Save It to Your Home Screen',['iPhone or iPad: open the app in Safari, then tap Share → Add to Home Screen → Add.','Android: open the app in Chrome, then choose Install app or Add to Home screen.','If the link opens inside Messages, Facebook or another app, open it in Safari or Chrome first.']],
['Create or Join a Round',['One golfer creates a protected 9- or 18-hole round.','Share the six-character code, join link or QR code. Every participant signs in before joining.','Use Resume Current Round if you leave the playing screen.','The three-line menu includes Home, Playing Tee, Round, code/QR, Courses/Players, Language and My Account.','English is the default. The app remembers the language selected on this device.']],
['Google Maps Course View',['Terrain and Satellite are the two map choices.','Every hole opens fitted and slightly tilted from the selected tee toward the green.','Pinch, drag, rotate and tilt supported maps; use the crosshair to restore the complete aligned hole.','Hole, distance, par, route remaining, weather and playing-direction wind remain visible.','Use the edge arrows to change holes and the three-line button to open the round menu.']],
['Shot Planner & Suggested Club',['Move the gold aim marker to choose a landing area.','The solid line shows yards to hit; the dotted route shows yards to go.','Aim 1 and Aim 2 guide doglegs, and the planner advances from your GPS position.','Suggested Club uses your saved carry distances and stops recommending Driver after the tee area.','Club suggestions are guidance only; consider wind, lie, elevation, hazards and shot shape.']],
['Protected Scoring',['Your score begins at the hole par. Use −, + or tap the score for exact strokes and optional putts.','Each signed-in golfer can edit only their own score.','The live scorecard updates for the group; offline scores synchronize after reconnecting.','You can share or download a branded scorecard image.']],
['Private Round Chat & Photos',['Message everyone in the current round and see unread indicators.','Take or choose a photo, add an optional caption, and tap shared photos to view or save them.','When the host permanently deletes the round, its stored chat photos are removed.']],
['Courses, Account & History',['The app recommends up to seven courses using location, favorites, recent play and mapping completeness. Search and filters reveal the full approved library.','Favorite courses on this device, or tap a course name or map to start a round.','Previous Rounds stores completed and in-progress scorecards; an active round includes Back to Game.','Approved courses may contain provisional GPS points and can be corrected before play.','Royale Jakarta pairings combine two of its North, South and West nines into one continuous 18-hole scorecard.','Authorized administrators can map tees, aim points and front, center and back of greens.']],
['Location & Privacy',['Allow precise location for live yardage, direction alignment and club suggestions.','Scores, messages and photos are limited to round participants. Contact information is available only to you and the Super Admin.']]],
contact:'Suggestions for improving the app are welcome.',close:'Close & Return Home',version:'Current feature guide · Version 101 · Updated August 31, 2026'},
es:{summary:'Guía de la aplicación y Acerca de',created:'CREADA PARA LA COMUNIDAD',about:'Una aplicación de golf creada por Rick Kulon para reunir compañerismo, orientación del campo, puntuación y comunicación grupal en una sola aplicación sencilla.',sections:[
['Antes de su primera ronda',['Toque Registrarse e introduzca nombre, apellido, correo electrónico y teléfono.','Confirme su cuenta desde el correo de Supabase; después regrese e inicie sesión. El dispositivo recordará su sesión.','Abra Mi cuenta → Mi perfil y foto para completar el perfil.','Abra Mis palos y distancias y guarde la distancia de vuelo habitual de cada palo.']],
['Guardar en la pantalla de inicio',['iPhone o iPad: abra la aplicación en Safari y toque Compartir → Añadir a pantalla de inicio → Añadir.','Android: ábrala en Chrome y elija Instalar aplicación o Añadir a pantalla de inicio.','Si el enlace se abre en Mensajes, Facebook u otra aplicación, ábralo primero en Safari o Chrome.']],
['Crear o unirse a una ronda',['Un jugador crea una ronda protegida de 9 o 18 hoyos.','Comparta el código de seis caracteres, el enlace o el código QR. Cada participante inicia sesión antes de unirse.','Use Reanudar ronda actual si sale de la pantalla de juego.','El menú de tres líneas incluye Inicio, Tee de juego, Ronda, código/QR, Campos/Jugadores, Idioma y Mi cuenta.','El inglés es el idioma predeterminado. La aplicación recuerda el idioma elegido en este dispositivo.']],
['Vista del campo en Google Maps',['Terreno y Satélite son las dos vistas disponibles.','Cada hoyo se abre encuadrado y ligeramente inclinado desde el tee elegido hacia el green.','Pellizque, arrastre, gire e incline; use la mira para restaurar el hoyo completo.','Hoyo, distancia, par, recorrido restante, clima y viento permanecen visibles.','Use las flechas laterales para cambiar de hoyo y el botón de tres líneas para abrir el menú.']],
['Planificador de tiro y palo sugerido',['Mueva el objetivo dorado para elegir la zona de caída.','La línea continua muestra la distancia del golpe; la línea punteada muestra la distancia restante.','Objetivo 1 y Objetivo 2 guían los doglegs; el planificador avanza desde su posición GPS.','El palo sugerido usa sus distancias guardadas y deja de recomendar Driver después del tee.','La recomendación es solo orientativa: considere viento, lie, elevación, obstáculos y forma del golpe.']],
['Puntuación protegida',['La puntuación empieza en el par. Use −, + o toque el marcador para golpes exactos y putts opcionales.','Cada jugador conectado solo puede editar su propia puntuación.','La tarjeta en vivo se actualiza para el grupo; los resultados sin conexión se sincronizan al reconectar.','Puede compartir o descargar una tarjeta con la marca ATG.']],
['Chat privado y fotos',['Envíe mensajes a todos los participantes y vea indicadores de mensajes nuevos.','Tome o elija una foto, añada un pie opcional y toque una foto compartida para verla o guardarla.','Si el anfitrión elimina permanentemente la ronda, también se eliminan sus fotos del chat.']],
['Campos, cuenta e historial',['La aplicación recomienda hasta siete campos según ubicación, favoritos, partidas recientes y calidad del mapeo. La búsqueda y los filtros muestran la biblioteca completa.','Marque favoritos o toque el nombre o mapa de un campo para iniciar una ronda.','Partidas anteriores guarda tarjetas terminadas y en curso; una ronda activa muestra Volver al juego.','Los campos aprobados pueden tener puntos GPS provisionales que se pueden corregir antes de jugar.','Royale Jakarta combina dos recorridos de nueve hoyos —North, South y West— en una tarjeta continua de 18 hoyos.','Los administradores autorizados pueden mapear tees, objetivos y frente, centro y fondo del green.']],
['Ubicación y privacidad',['Permita ubicación precisa para yardas en vivo, orientación y recomendaciones de palo.','Puntuaciones, mensajes y fotos se limitan a los participantes. Los datos de contacto solo son visibles para usted y el Superadministrador.']]],contact:'Se agradecen las sugerencias para mejorar la aplicación.',close:'Cerrar y volver al inicio',version:'Guía actual · Versión 101 · Actualizada el 31 de agosto de 2026'},
zh:{summary:'应用指南与关于',created:'为团契而创建',about:'Rick Kulon 创建的移动高尔夫助手，将团契、球场导航、记分和小组沟通整合在一个简单的应用中。',sections:[
['第一次打球前',['点击注册，填写名字、姓氏、电子邮件和电话号码。','通过 Supabase 验证邮件确认账户，然后返回并登录。本设备会记住登录状态。','打开“我的账户 → 我的资料与照片”完成个人资料。','打开“我的球杆与距离”，保存每支球杆通常的飞行距离。']],
['保存到主屏幕',['iPhone 或 iPad：在 Safari 中打开，点击“共享 → 添加到主屏幕 → 添加”。','Android：在 Chrome 中打开，选择“安装应用”或“添加到主屏幕”。','如果链接在“信息”、Facebook 或其他应用中打开，请先选择在 Safari 或 Chrome 中打开。']],
['创建或加入球局',['一名球员创建受保护的 9 洞或 18 洞球局。','分享六位代码、加入链接或二维码；所有参与者须先登录。','离开打球画面后，使用“继续当前球局”返回。','三线菜单包括主页、发球台、球局、代码/二维码、球场/球员、语言和我的账户。','英语为默认语言，应用会记住本设备选择的语言。']],
['Google Maps 球场视图',['可在地形和卫星两种视图间切换。','每一洞都会从所选发球台朝果岭自动完整取景并稍微倾斜。','可缩放、拖动、旋转和倾斜；点击准星可恢复完整对齐视图。','洞号、距离、标准杆、剩余路线、天气和相对打球方向的风保持可见。','使用两侧箭头切换球洞，使用三线按钮打开球局菜单。']],
['击球规划器与建议球杆',['移动金色目标标记来选择落点。','实线显示击球距离，虚线路线显示剩余距离。','目标点 1 和 2 用于狗腿洞；规划器会从您的 GPS 位置向前移动。','建议球杆使用您保存的携带距离，离开发球区后不再建议一号木。','建议仅供参考，请考虑风、球位、高差、障碍和球路。']],
['受保护记分',['分数从本洞标准杆开始；使用 −、+，或点击分数输入准确杆数和可选推杆数。','每位已登录球员只能编辑自己的分数。','实时记分卡会为小组更新；离线分数会在重新连接后同步。','可以分享或下载带 ATG 品牌的记分卡图片。']],
['私人球局聊天与照片',['向当前球局所有参与者发送消息，并查看未读提示。','拍摄或选择照片、添加可选说明，点击共享照片可查看或保存。','主持人永久删除球局时，其聊天照片也会从存储中删除。']],
['球场、账户与历史',['应用根据位置、收藏、最近打球和地图完整度推荐最多七个球场；搜索和筛选可查看完整资料库。','可在本设备收藏球场，或点击球场名称/地图开始球局。','历史球局保存已完成和进行中的记分卡；有活动球局时会显示“返回球局”。','已批准球场可能含临时 GPS 点，打球前可以修正。','Royale Jakarta 会从 North、South、West 三个九洞中组合两个，显示为连续的 18 洞记分卡。','授权管理员可以标记发球台、目标点和果岭前部、中心与后部。']],
['位置与隐私',['允许精确位置以获得实时码数、方向对齐和球杆建议。','分数、消息和照片仅限球局参与者；联系方式仅您本人和超级管理员可见。']]],contact:'欢迎提出改进应用的建议。',close:'关闭并返回主页',version:'当前功能指南 · 版本 101 · 2026年8月31日更新'},
id:{summary:'Panduan Aplikasi & Tentang',created:'DIBUAT UNTUK PERSEKUTUAN',about:'Pendamping golf seluler yang dibuat oleh Rick Kulon untuk menyatukan persekutuan, panduan lapangan, pencatatan skor, dan komunikasi kelompok dalam satu aplikasi sederhana.',sections:[
['Sebelum Ronde Pertama',['Ketuk Daftar dan masukkan nama depan, nama belakang, email, serta nomor telepon.','Konfirmasikan akun melalui email verifikasi Supabase, lalu kembali dan masuk. Perangkat ini akan mengingat login Anda.','Buka Akun Saya → Profil & Foto Saya untuk melengkapi profil.','Buka Klub & Jarak Saya dan simpan jarak carry normal setiap klub.']],
['Simpan ke Layar Utama',['iPhone atau iPad: buka aplikasi di Safari, lalu ketuk Bagikan → Tambahkan ke Layar Utama → Tambah.','Android: buka di Chrome, lalu pilih Instal aplikasi atau Tambahkan ke layar utama.','Jika tautan terbuka di Pesan, Facebook, atau aplikasi lain, buka terlebih dahulu di Safari atau Chrome.']],
['Membuat atau Bergabung ke Ronde',['Satu pegolf membuat ronde terlindungi 9 atau 18 hole.','Bagikan kode enam karakter, tautan bergabung, atau kode QR. Setiap peserta masuk sebelum bergabung.','Gunakan Lanjutkan Ronde Saat Ini jika Anda meninggalkan layar permainan.','Menu tiga garis berisi Beranda, Tee Bermain, Ronde, kode/QR, Lapangan/Pemain, Bahasa, dan Akun Saya.','Bahasa Inggris adalah default. Aplikasi mengingat bahasa yang dipilih pada perangkat ini.']],
['Tampilan Lapangan Google Maps',['Medan dan Satelit adalah dua pilihan peta.','Setiap hole terbuka dengan seluruh rute terlihat dan sedikit miring dari tee pilihan menuju green.','Cubit, geser, putar, dan miringkan peta; gunakan bidik untuk memulihkan tampilan penuh yang sejajar.','Hole, jarak, par, sisa rute, cuaca, dan arah angin relatif tetap terlihat.','Gunakan panah samping untuk berpindah hole dan tombol tiga garis untuk membuka menu ronde.']],
['Perencana Pukulan & Saran Klub',['Pindahkan penanda sasaran emas untuk memilih area jatuh bola.','Garis penuh menunjukkan jarak pukulan; rute putus-putus menunjukkan sisa jarak.','Aim 1 dan Aim 2 memandu dogleg; perencana bergerak maju dari posisi GPS Anda.','Saran Klub memakai jarak carry tersimpan dan berhenti menyarankan Driver setelah area tee.','Saran hanya panduan; pertimbangkan angin, lie, elevasi, bahaya, dan bentuk pukulan.']],
['Skor Terlindungi',['Skor dimulai dari par hole. Gunakan −, +, atau ketuk skor untuk jumlah pukulan tepat dan putt opsional.','Setiap pegolf yang masuk hanya dapat mengubah skornya sendiri.','Kartu skor langsung diperbarui untuk grup; skor offline disinkronkan setelah tersambung kembali.','Kartu skor bermerek ATG dapat dibagikan atau diunduh.']],
['Obrolan Ronde Pribadi & Foto',['Kirim pesan kepada semua peserta ronde dan lihat indikator pesan belum dibaca.','Ambil atau pilih foto, tambahkan keterangan opsional, lalu ketuk foto bersama untuk melihat atau menyimpan.','Jika tuan rumah menghapus ronde secara permanen, foto obrolannya juga dihapus dari penyimpanan.']],
['Lapangan, Akun & Riwayat',['Aplikasi merekomendasikan hingga tujuh lapangan berdasarkan lokasi, favorit, permainan terbaru, dan kelengkapan pemetaan. Pencarian dan filter menampilkan seluruh pustaka.','Favoritkan lapangan pada perangkat ini atau ketuk nama/peta lapangan untuk memulai ronde.','Ronde Sebelumnya menyimpan kartu skor selesai dan berjalan; ronde aktif menampilkan Kembali ke Ronde.','Lapangan yang disetujui mungkin masih memakai titik GPS sementara yang dapat diperbaiki sebelum bermain.','Royale Jakarta menggabungkan dua dari sembilan hole North, South, dan West menjadi satu kartu skor 18 hole berurutan.','Administrator resmi dapat memetakan tee, titik sasaran, serta bagian depan, tengah, dan belakang green.']],
['Lokasi & Privasi',['Izinkan lokasi akurat untuk yard GPS langsung, penyelarasan arah, dan saran klub.','Skor, pesan, dan foto hanya untuk peserta ronde. Informasi kontak hanya tersedia bagi Anda dan Super Admin.']]],contact:'Saran untuk meningkatkan aplikasi sangat kami hargai.',close:'Tutup & Kembali ke Beranda',version:'Panduan fitur saat ini · Versi 101 · Diperbarui 31 Agustus 2026'},
hi:{summary:'ऐप गाइड और परिचय',created:'संगति के लिए बनाया गया',about:'रिक कुलोन द्वारा बनाया गया मोबाइल गोल्फ साथी, जो संगति, कोर्स मार्गदर्शन, स्कोरिंग और समूह संचार को एक सरल ऐप में जोड़ता है।',sections:[
['पहले राउंड से पहले',['साइन अप पर टैप करके पहला नाम, अंतिम नाम, ईमेल और फोन नंबर भरें।','Supabase सत्यापन ईमेल से खाता पक्का करें, फिर लौटकर साइन इन करें। इस डिवाइस पर लॉगिन याद रहेगा।','मेरा खाता → मेरी प्रोफ़ाइल और चित्र खोलकर प्रोफ़ाइल पूरी करें।','मेरे क्लब और दूरियाँ खोलकर हर क्लब की सामान्य कैरी दूरी सेव करें।']],
['होम स्क्रीन पर सेव करें',['iPhone या iPad: Safari में ऐप खोलें और Share → Add to Home Screen → Add चुनें।','Android: Chrome में खोलें और Install app या Add to Home screen चुनें।','यदि लिंक Messages, Facebook या किसी अन्य ऐप में खुले, तो पहले Safari या Chrome में खोलें।']],
['राउंड बनाएँ या जुड़ें',['एक खिलाड़ी सुरक्षित 9 या 18 होल राउंड बनाता है।','छह-अक्षर कोड, जॉइन लिंक या QR साझा करें; हर खिलाड़ी जुड़ने से पहले साइन इन करे।','खेल स्क्रीन से बाहर होने पर वर्तमान राउंड जारी रखें का उपयोग करें।','तीन-लाइन मेनू में होम, खेलने की टी, राउंड, कोड/QR, कोर्स/खिलाड़ी, भाषा और मेरा खाता है।','अंग्रेज़ी डिफ़ॉल्ट है; ऐप इस डिवाइस पर चुनी भाषा याद रखता है।']],
['Google Maps कोर्स दृश्य',['टेरेन और सैटेलाइट दो मानचित्र विकल्प हैं।','हर होल चुनी गई टी से ग्रीन तक पूरा फिट होकर हल्के झुकाव में खुलता है।','ज़ूम, ड्रैग, घुमाएँ और समर्थित मानचित्र झुकाएँ; पूरा संरेखित होल लौटाने के लिए क्रॉसहेयर दबाएँ।','होल, दूरी, पार, शेष रूट, मौसम और खेल दिशा के अनुसार हवा दिखाई देती रहती है।','होल बदलने के लिए किनारे के तीर और मेनू के लिए तीन-लाइन बटन उपयोग करें।']],
['शॉट प्लानर और सुझाया क्लब',['लैंडिंग क्षेत्र चुनने के लिए सुनहरा लक्ष्य मार्कर खिसकाएँ।','ठोस रेखा हिट की दूरी और बिंदीदार रूट शेष दूरी दिखाता है।','Aim 1 और Aim 2 डॉगलेग में मार्गदर्शन करते हैं; प्लानर GPS स्थिति से आगे बढ़ता है।','सुझाया क्लब सेव की गई कैरी दूरी उपयोग करता है और टी क्षेत्र के बाद Driver सुझाना बंद करता है।','यह केवल मार्गदर्शन है; हवा, लाई, ऊँचाई, खतरे और शॉट आकार पर विचार करें।']],
['सुरक्षित स्कोरिंग',['स्कोर होल के पार से शुरू होता है। −, + या सटीक स्ट्रोक और वैकल्पिक पुट के लिए स्कोर टैप करें।','हर साइन-इन खिलाड़ी केवल अपना स्कोर बदल सकता है।','लाइव स्कोरकार्ड समूह के लिए अपडेट होता है; ऑफलाइन स्कोर दोबारा कनेक्ट होने पर सिंक होते हैं।','ATG ब्रांड वाला स्कोरकार्ड साझा या डाउनलोड किया जा सकता है।']],
['निजी राउंड चैट और फोटो',['वर्तमान राउंड के सभी खिलाड़ियों को संदेश भेजें और अपठित संकेत देखें।','फोटो लें या चुनें, वैकल्पिक कैप्शन जोड़ें और साझा फोटो देखने या सेव करने के लिए टैप करें।','होस्ट द्वारा राउंड स्थायी रूप से हटाने पर उसकी चैट फोटो भी स्टोरेज से हटती हैं।']],
['कोर्स, खाता और इतिहास',['ऐप स्थान, पसंदीदा, हाल के खेल और मैपिंग पूर्णता के आधार पर सात तक कोर्स सुझाता है; खोज और फ़िल्टर पूरी लाइब्रेरी दिखाते हैं।','इस डिवाइस पर कोर्स पसंदीदा बनाएँ या नाम/मानचित्र टैप करके राउंड शुरू करें।','पिछले मैच पूर्ण और चल रहे स्कोरकार्ड रखते हैं; सक्रिय राउंड में राउंड पर लौटें दिखाई देता है।','स्वीकृत कोर्स में अस्थायी GPS बिंदु हो सकते हैं जिन्हें खेलने से पहले सुधारा जा सकता है।','Royale Jakarta के North, South और West में से दो नौ-होल को एक लगातार 18-होल स्कोरकार्ड में जोड़ा जाता है।','अधिकृत प्रशासक टी, लक्ष्य बिंदु और ग्रीन का आगे, केंद्र व पीछे मैप कर सकते हैं।']],
['स्थान और गोपनीयता',['लाइव दूरी, दिशा संरेखण और क्लब सुझावों के लिए सटीक स्थान की अनुमति दें।','स्कोर, संदेश और फोटो केवल राउंड खिलाड़ियों के लिए हैं। संपर्क जानकारी केवल आपको और Super Admin को दिखती है।']]],contact:'ऐप सुधारने के सुझावों का स्वागत है।',close:'बंद करें और होम लौटें',version:'वर्तमान फीचर गाइड · संस्करण 101 · 31 अगस्त 2026 को अपडेट'},
fr:{summary:'Guide de l’application et À propos',created:'CRÉÉ POUR LA FRATERNITÉ',about:'Un compagnon de golf mobile créé par Rick Kulon pour réunir fraternité, guidage du parcours, score et communication de groupe dans une application simple.',sections:[
['Avant votre première partie',['Touchez S’inscrire et saisissez prénom, nom, courriel et téléphone.','Confirmez le compte depuis le courriel Supabase, puis revenez vous connecter. La connexion est mémorisée sur cet appareil.','Ouvrez Mon compte → Mon profil et ma photo pour compléter votre profil.','Ouvrez Mes clubs et distances et enregistrez la distance de vol habituelle de chaque club.']],
['Enregistrer sur l’écran d’accueil',['iPhone ou iPad : ouvrez dans Safari, puis touchez Partager → Sur l’écran d’accueil → Ajouter.','Android : ouvrez dans Chrome, puis choisissez Installer l’application ou Ajouter à l’écran d’accueil.','Si le lien s’ouvre dans Messages, Facebook ou une autre application, ouvrez-le d’abord dans Safari ou Chrome.']],
['Créer ou rejoindre une partie',['Un joueur crée une partie protégée de 9 ou 18 trous.','Partagez le code à six caractères, le lien ou le QR. Chaque participant se connecte avant de rejoindre.','Utilisez Reprendre la partie en cours si vous quittez l’écran de jeu.','Le menu à trois lignes comprend Accueil, Tee de départ, Partie, code/QR, Parcours/Joueurs, Langue et Mon compte.','L’anglais est la langue par défaut. L’application mémorise la langue choisie sur cet appareil.']],
['Vue Google Maps du parcours',['Relief et Satellite sont les deux choix de carte.','Chaque trou s’ouvre cadré et légèrement incliné du tee choisi vers le green.','Pincez, déplacez, tournez et inclinez les cartes compatibles ; utilisez le réticule pour restaurer le trou complet.','Trou, distance, par, trajet restant, météo et vent relatif au sens de jeu restent visibles.','Utilisez les flèches latérales pour changer de trou et le bouton à trois lignes pour le menu.']],
['Planificateur de coup et club suggéré',['Déplacez la cible dorée pour choisir la zone d’atterrissage.','La ligne pleine indique la distance du coup ; le trajet pointillé indique la distance restante.','Aim 1 et Aim 2 guident les doglegs ; le planificateur avance depuis votre position GPS.','Le club suggéré utilise vos distances enregistrées et cesse de proposer le Driver après la zone de départ.','Ce conseil reste indicatif : considérez vent, lie, dénivelé, obstacles et forme du coup.']],
['Score protégé',['Le score commence au par du trou. Utilisez −, + ou touchez le score pour saisir les coups exacts et les putts facultatifs.','Chaque joueur connecté ne peut modifier que son propre score.','La carte en direct se met à jour pour le groupe ; les scores hors ligne se synchronisent après reconnexion.','Vous pouvez partager ou télécharger une carte de score ATG.']],
['Discussion privée et photos',['Envoyez des messages à tous les participants et voyez les indicateurs non lus.','Prenez ou choisissez une photo, ajoutez une légende facultative et touchez une photo partagée pour la voir ou l’enregistrer.','Quand l’hôte supprime définitivement la partie, ses photos de discussion sont aussi supprimées.']],
['Parcours, compte et historique',['L’application recommande jusqu’à sept parcours selon la position, les favoris, les parties récentes et la qualité du mappage. Recherche et filtres ouvrent toute la bibliothèque.','Ajoutez des favoris sur cet appareil ou touchez le nom/la carte d’un parcours pour démarrer.','Parties précédentes conserve les cartes terminées et en cours ; une partie active affiche Retour à la partie.','Les parcours approuvés peuvent contenir des points GPS provisoires à corriger avant de jouer.','Royale Jakarta associe deux de ses neuf trous North, South et West en une carte continue de 18 trous.','Les administrateurs autorisés peuvent mapper tees, points de visée et avant, centre et fond des greens.']],
['Localisation et confidentialité',['Autorisez la position précise pour les distances en direct, l’orientation et les suggestions de club.','Scores, messages et photos sont limités aux participants. Les coordonnées ne sont visibles que par vous et le Super Admin.']]],contact:'Vos suggestions pour améliorer l’application sont les bienvenues.',close:'Fermer et revenir à l’accueil',version:'Guide actuel · Version 101 · Mis à jour le 31 août 2026'}
};
Object.values(guides).forEach(guide=>{guide.version=guide.version.replace('101','106')});
const list=items=>`<ul class="guide-features">${items.map(item=>`<li>${item}</li>`).join('')}</ul>`;
function render(lang){const g=guides[lang]||guides.en;return`<details class="app-guide" ontoggle="positionLocalizedGuide(this)"><summary><span>${g.summary}</span><b>＋</b></summary><div class="guide-body"><section class="founder-card"><img src="rick-kulon-profile.jpg" alt="Rick Kulon"><div><small class="guide-opening-line">${g.created}</small><h2>ParFolio</h2><p>${g.about}</p></div></section>${g.sections.map(([title,items],index)=>`${index===1?'':''}<h3>${title}</h3>${list(items)}`).join('')}<div class="guide-update">${g.version}</div><div class="guide-contact"><p>${g.contact}</p><a href="mailto:ricbkewl@gmail.com?subject=Agape%20Golf%20App%20Suggestion">✉ ricbkewl@gmail.com</a><a href="sms:+16074383208">✆ 607.438.3208</a></div><button class="guide-close-button" onclick="closeAppGuide(this)">${g.close}</button></div></details>`}
window.ATG_GUIDE={render};
})();
