/* ParFolio v248 — simplified Trace Studio entry with independent Club Trace and Ball Trace overlays. */
(function(){
 const ROLES=new Set(['course_admin','super_admin']);
 const loaded=new Map();let tracePromise=null,currentUrl=null;
 const access=()=>typeof adminRole!=='undefined'&&ROLES.has(adminRole);
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function styles(){if(document.querySelector('link[data-parfolio-ai-v225]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='parfolio-ai-v225.css?v=248';l.dataset.parfolioAiV225='1';document.head.appendChild(l);if(!document.getElementById('pf-trace-v248-style')){const s=document.createElement('style');s.id='pf-trace-v248-style';s.textContent=`
 .pf-trace-shell .pf-ai-body{max-width:920px;padding-top:12px}.pf-trace-toggle-row{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:4px 0 12px}.pf-trace-toggle{border:1px solid rgba(255,255,255,.13);background:rgba(255,255,255,.055);color:#fff;border-radius:16px;padding:14px 12px;text-align:left;display:flex;align-items:center;gap:10px}.pf-trace-toggle strong{display:block;font-size:14px}.pf-trace-toggle small{display:block;opacity:.68;margin-top:3px}.pf-trace-toggle .pf-trace-dot{width:12px;height:12px;border-radius:50%;background:#55615d;box-shadow:0 0 0 4px rgba(255,255,255,.04)}.pf-trace-toggle.active{border-color:rgba(240,203,91,.55);background:rgba(240,203,91,.11)}.pf-trace-toggle[data-trace=club].active .pf-trace-dot{background:#f0cb5b}.pf-trace-toggle[data-trace=ball].active .pf-trace-dot{background:#ff4f4f}.pf-trace-video-wrap{position:relative;border-radius:18px;overflow:hidden;background:#000;min-height:220px}.pf-trace-video-wrap video{display:block;width:100%;max-height:76vh;background:#000}.pf-trace-video-wrap canvas{position:absolute;inset:0;width:100%;height:100%;pointer-events:none}.pf-trace-video-wrap #pf-ai-club-canvas{z-index:2}.pf-trace-video-wrap #pf-ai-ball-canvas{z-index:3}.pf-trace-status{margin:8px 0 0;padding:8px 11px;border-radius:999px;background:rgba(5,15,12,.66);border:1px solid rgba(255,255,255,.08);font-size:11px}.pf-trace-corrections{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.pf-trace-corrections button{flex:1;min-width:120px}.pf-trace-legend{display:flex;gap:8px;flex-wrap:wrap;font-size:10px;opacity:.85;margin-top:8px}.pf-trace-legend span{display:flex;align-items:center;gap:4px}.pf-trace-legend i{width:8px;height:8px;border-radius:50%;display:inline-block}.pf-trace-empty{padding:18px;border:1px dashed rgba(255,255,255,.14);border-radius:16px;text-align:center;opacity:.74;margin-top:10px}
 @media(max-width:430px){.pf-trace-toggle-row{gap:7px}.pf-trace-toggle{padding:12px 9px;border-radius:14px}.pf-trace-toggle strong{font-size:13px}.pf-trace-toggle small{font-size:10px}.pf-trace-corrections button{min-width:92px;padding:9px 8px;font-size:11px}.pf-trace-video-wrap video{max-height:72vh}}
 `;document.head.appendChild(s)}}
 function loadScript(src,key){if(loaded.has(key))return loaded.get(key);const p=new Promise((resolve,reject)=>{const old=document.querySelector(`script[data-pf-ai-lazy="${key}"]`);if(old){if(old.dataset.ready==='1')return resolve();old.addEventListener('load',resolve,{once:true});old.addEventListener('error',reject,{once:true});return}const s=document.createElement('script');s.src=src;s.async=true;s.dataset.pfAiLazy=key;s.onload=()=>{s.dataset.ready='1';resolve()};s.onerror=reject;document.head.appendChild(s)});loaded.set(key,p);return p}
 function loadTrace(){if(tracePromise)return tracePromise;tracePromise=loadScript('parfolio-dual-trace-v248.js?v=248','trace248');return tracePromise}
 function close(){document.querySelector('.pf-ai-shell')?.remove();if(currentUrl){URL.revokeObjectURL(currentUrl);currentUrl=null}}window.closeParFolioAI=close;
 function shell(title,sub,body){styles();close();const e=document.createElement('section');e.className='pf-ai-shell pf-trace-shell';e.innerHTML=`<header class="pf-ai-top"><button class="pf-ai-back">‹</button><div><div class="pf-ai-kicker">PARFOLIO AI</div><h2>${esc(title)}</h2><p>${esc(sub)}</p></div><span class="pf-ai-pro">ADMIN PREVIEW</span></header><div class="pf-ai-body">${body}</div>`;e.querySelector('.pf-ai-back').onclick=close;document.body.appendChild(e);return e}
 const picker=()=>`<div class="pf-ai-source-grid"><label class="pf-ai-source-button"><input id="pf-ai-trace-record" type="file" accept="video/*" capture="environment"><span class="pf-ai-upload-icon">●</span><strong>Record Video</strong><small>Record the complete swing and ball flight.</small></label><label class="pf-ai-source-button"><input id="pf-ai-trace-choose" type="file" accept="video/*"><span class="pf-ai-upload-icon">▣</span><strong>Choose Existing Video</strong><small>Select a golf video from your device.</small></label></div><div class="pf-ai-source-note">Keep the golfer, clubhead, ball, and launch area visible. High frame rate helps both traces.</div>`;
 window.openParFolioAI=function(){if(!access())return false;const e=shell('Trace Studio','Trace the club, the ball, or both on the same video.',`${picker()}<div id="pf-ai-trace-editor" hidden><div class="pf-trace-toggle-row"><button class="pf-trace-toggle" data-trace="club"><span class="pf-trace-dot"></span><div><strong>Club Trace</strong><small>Follow the clubhead through the swing.</small></div></button><button class="pf-trace-toggle" data-trace="ball"><span class="pf-trace-dot"></span><div><strong>Ball Trace</strong><small>Follow the ball flight after impact.</small></div></button></div><div class="pf-trace-video-wrap"><video id="pf-ai-trace-video" controls playsinline preload="metadata"></video><canvas id="pf-ai-club-canvas"></canvas><canvas id="pf-ai-ball-canvas"></canvas></div><div id="pf-ai-trace-status" class="pf-trace-status">Choose a video, then turn on Club Trace, Ball Trace, or both.</div><div id="pf-ai-trace-help" class="pf-ai-instructions"><strong>Two independent overlays.</strong> Turn either trace on or off at any time.</div><div class="pf-trace-corrections"><button id="pf-ai-seed-club">Seed Clubhead</button><button id="pf-ai-seed-ball">Seed Ball</button><button id="pf-ai-trace-reset">Reset Traces</button></div><div class="pf-trace-legend"><span><i style="background:#58d8ff"></i>Takeaway</span><span><i style="background:#a985ff"></i>Top</span><span><i style="background:#ff9f43"></i>Downswing</span><span><i style="background:#ff4f4f"></i>Impact / Ball</span><span><i style="background:#60d394"></i>Release</span><span><i style="background:#e9f2ee"></i>Finish</span></div></div>`);const ed=e.querySelector('#pf-ai-trace-editor'),v=e.querySelector('#pf-ai-trace-video'),st=e.querySelector('#pf-ai-trace-status');const useFile=async f=>{if(currentUrl)URL.revokeObjectURL(currentUrl);currentUrl=URL.createObjectURL(f);v.src=currentUrl;v.preload='metadata';ed.hidden=false;e.querySelectorAll('[data-trace]').forEach(b=>b.classList.remove('active'));st.textContent='Video ready. Turn on Club Trace, Ball Trace, or both.';try{await loadTrace();window.ParFolioTraceStudio?.attach?.()}catch(err){console.error('ParFolio Trace Studio:',err);st.textContent='Trace Studio could not load on this device.'}};['record','choose'].forEach(type=>{const i=e.querySelector('#pf-ai-trace-'+type);i.onchange=()=>{const f=i.files?.[0];if(f)useFile(f)}});return true};
 window.openSwingAI=window.openParFolioAI;window.openShotVision=window.openParFolioAI;
 function menu(){document.querySelectorAll('.app-side-menu.menu-v204').forEach(m=>{if(!access()){m.querySelectorAll('[data-parfolio-ai-menu]').forEach(n=>n.remove());close();return}if(m.querySelector('[data-parfolio-ai-menu]'))return;const settings=[...m.querySelectorAll('.menu-section-label')].find(x=>/SETTINGS|AJUSTES|设置|PENGATURAN|सेटिंग्स|RÉGLAGES/i.test(x.textContent)),l=document.createElement('div'),b=document.createElement('button');l.className='menu-section-label';l.dataset.parfolioAiMenu='1';l.textContent='PARFOLIO AI';b.className='pf-ai-menu-button';b.dataset.parfolioAiMenu='1';b.innerHTML='<span class="menu-line-icon">✦</span><div>Trace Studio<small>Club Trace + Ball Trace</small></div>';b.onclick=()=>{if(typeof closeRoundQuickMenu==='function')closeRoundQuickMenu();openParFolioAI()};if(settings){m.insertBefore(l,settings);m.insertBefore(b,settings)}else{m.append(l,b)}})}
 new MutationObserver(menu).observe(document.body,{childList:true,subtree:true});menu();window.ParFolioAI={open:window.openParFolioAI,openSwing:window.openParFolioAI,openShot:window.openParFolioAI,hasAccess:access,version:248};
})();