/* ParFolio v245 — lightweight AI shell with validated analytics/coach lazy loading. */
(function(){
 const S={shot:null,swing:null,mode:'video',paths:{back:[],down:[]},plane:[]},ROLES=new Set(['course_admin','super_admin']);
 const loaded=new Map();let swingModulesPromise=null,shotModulePromise=null;
 const access=()=>typeof adminRole!=='undefined'&&ROLES.has(adminRole);
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function styles(){if(document.querySelector('link[data-parfolio-ai-v225]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='parfolio-ai-v225.css?v=244';l.dataset.parfolioAiV225='1';document.head.appendChild(l)}
 function loadScript(src,key){if(loaded.has(key))return loaded.get(key);const p=new Promise((resolve,reject)=>{const existing=document.querySelector(`script[data-pf-ai-lazy="${key}"]`);if(existing){if(existing.dataset.ready==='1')return resolve();existing.addEventListener('load',()=>resolve(),{once:true});existing.addEventListener('error',reject,{once:true});return}const s=document.createElement('script');s.src=src;s.async=true;s.dataset.pfAiLazy=key;s.onload=()=>{s.dataset.ready='1';resolve()};s.onerror=reject;document.head.appendChild(s)});loaded.set(key,p);return p}
 function loadSwingModules(){if(swingModulesPromise)return swingModulesPromise;swingModulesPromise=(async()=>{await loadScript('parfolio-pose-trace-v229.js?v=244','pose');await loadScript('parfolio-hand-path-v230.js?v=244','hand');await loadScript('parfolio-swing-analytics-v231.js?v=245','analytics');await loadScript('parfolio-club-track-v232.js?v=244','club');await loadScript('parfolio-phase-motion-v233.js?v=244','phase');await loadScript('parfolio-ai-coach-v234.js?v=245','coach')})();return swingModulesPromise}
 function loadShotModule(){if(shotModulePromise)return shotModulePromise;shotModulePromise=loadScript('parfolio-shot-vision-v235.js?v=241','shot');return shotModulePromise}
 function close(){document.querySelector('.pf-ai-shell')?.remove()}window.closeParFolioAI=close;
 function shell(title,sub,body){styles();close();const e=document.createElement('section');e.className='pf-ai-shell';e.innerHTML=`<header class="pf-ai-top"><button class="pf-ai-back">‹</button><div><div class="pf-ai-kicker">PARFOLIO AI</div><h2>${esc(title)}</h2><p>${esc(sub)}</p></div><span class="pf-ai-pro">ADMIN PREVIEW</span></header><div class="pf-ai-body">${body}</div>`;e.querySelector('.pf-ai-back').onclick=()=>title==='Swing AI'||title==='Shot Vision'?openParFolioAI():close();document.body.appendChild(e);return e}
 window.openParFolioAI=function(){if(!access())return false;const e=shell('Improve Your Game','Swing mechanics, club path and ball-flight tools.',`<div class="pf-ai-hero"><div class="pf-ai-mark">PF</div><div><strong>ParFolio AI</strong><span>See the swing. See the shot. Improve the pattern.</span></div></div><div class="pf-ai-grid"><button class="pf-ai-card" data-open="swing"><span class="pf-ai-card-icon">◎</span><div><strong>Swing AI</strong><small>Video, body landmarks, club path, plane, analytics and coaching workspace.</small></div><b>›</b></button><button class="pf-ai-card" data-open="shot"><span class="pf-ai-card-icon">↗</span><div><strong>Shot Vision</strong><small>Create and refine a ball-flight tracer over your shot video.</small></div><b>›</b></button></div><div class="pf-ai-note"><strong>Lightweight preview</strong><span>Analysis engines remain unloaded until you choose a video and request analysis.</span></div>`);e.querySelector('[data-open="swing"]').onclick=openSwingAI;e.querySelector('[data-open="shot"]').onclick=openShotVision;return true};
 const picker=k=>`<div class="pf-ai-source-grid"><label class="pf-ai-source-button"><input id="pf-ai-${k}-record" type="file" accept="video/*" capture="environment"><span class="pf-ai-upload-icon">●</span><strong>Record Video</strong><small>Open the camera and record a new golf video.</small></label><label class="pf-ai-source-button"><input id="pf-ai-${k}-choose" type="file" accept="video/*"><span class="pf-ai-upload-icon">▣</span><strong>Choose Existing Video</strong><small>Select a video already saved on your phone or tablet.</small></label></div><div class="pf-ai-source-note">Stable camera, full golfer and club in frame. High frame rate is preferred.</div>`;
 function canvasSize(c,v){const r=v.getBoundingClientRect(),w=Math.max(1,Math.round(r.width)),h=Math.max(1,Math.round(r.height));if(c.width!==w||c.height!==h){c.width=w;c.height=h}return[w,h]}
 function drawSwing(c,v){const x=c.getContext('2d'),[w,h]=canvasSize(c,v);x.clearRect(0,0,w,h);if(S.mode==='video'||S.mode==='analytics'||S.mode==='coach')return;if(S.mode==='plane'&&S.plane.length===2){x.beginPath();x.moveTo(S.plane[0].x*w,S.plane[0].y*h);x.lineTo(S.plane[1].x*w,S.plane[1].y*h);x.strokeStyle='#f0cb5b';x.lineWidth=3;x.setLineDash([10,7]);x.stroke();x.setLineDash([])}}
 function pt(e,c){const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height}}
 function bindVideoSources(e,kind,onFile){['record','choose'].forEach(type=>{const input=e.querySelector(`#pf-ai-${kind}-${type}`);input.onchange=()=>{const f=input.files?.[0];if(f)onFile(f)}})}
 window.openSwingAI=function(){if(!access())return false;S.mode='video';const e=shell('Swing AI','Analyze body motion, club path and swing plane.',`<div class="pf-ai-form-row"><label>Camera view<select id="pf-ai-swing-view"><option value="dtl">Down the line</option><option value="face">Face on</option></select></label><label>Club<select id="pf-ai-swing-club"><option>Driver</option><option>3 Wood</option><option>Hybrid</option><option>7 Iron</option><option>Wedge</option><option>Putter</option></select></label></div>${picker('swing')}<div id="pf-ai-swing-editor" class="pf-ai-editor" hidden><div class="pf-ai-mode-row"><button data-mode="video" class="active">Video</button><button data-mode="skeleton">Skeleton</button><button data-mode="path">Club Path</button><button data-mode="plane">Plane</button><button data-mode="analytics">Analytics</button><button data-mode="coach">AI Coach</button></div><div class="pf-ai-video-wrap"><video id="pf-ai-swing-video" controls playsinline preload="metadata"></video><canvas id="pf-ai-swing-canvas" style="display:none"></canvas></div><div id="pf-ai-swing-help" class="pf-ai-instructions">Video mode. Native playback only; no AI engine is loaded.</div><div class="pf-ai-phase-row"><button data-phase="Address">Address</button><button data-phase="Takeaway">Takeaway</button><button data-phase="Top">Top</button><button data-phase="Downswing">Downswing</button><button data-phase="Impact">Impact</button><button data-phase="Release">Release</button><button data-phase="Finish">Finish</button></div><div id="pf-ai-analysis-panel" class="pf-ai-analysis-panel"><strong>Video ready workspace</strong><span>Choose a video first. Analysis code loads only when you select an analysis mode.</span></div><div class="pf-ai-actions"><button id="pf-ai-overlay-clear">Clear overlay</button><button id="pf-ai-swing-save" class="pf-ai-primary">Save swing draft</button></div><div id="pf-ai-swing-phase" class="pf-ai-status">Choose or record a swing video.</div></div>`);
 const ed=e.querySelector('#pf-ai-swing-editor'),v=e.querySelector('#pf-ai-swing-video'),c=e.querySelector('#pf-ai-swing-canvas'),status=e.querySelector('#pf-ai-swing-phase'),help=e.querySelector('#pf-ai-swing-help'),panel=e.querySelector('#pf-ai-analysis-panel');
 const setCanvasMode=()=>{c.style.pointerEvents=S.mode==='plane'?'auto':'none';c.style.display=S.mode==='video'?'none':'block'};
 bindVideoSources(e,'swing',f=>{if(S.swing?.url)URL.revokeObjectURL(S.swing.url);S.swing={file:f,url:URL.createObjectURL(f),marks:{},landmarks:{}};S.plane=[];S.mode='video';e.querySelectorAll('[data-mode]').forEach(q=>q.classList.toggle('active',q.dataset.mode==='video'));v.src=S.swing.url;v.preload='metadata';ed.hidden=false;setCanvasMode();status.textContent='Video ready. Press Play. AI is not loaded in Video mode.';help.textContent='Video mode. Native playback only; no AI engine is loaded.';panel.innerHTML='<strong>Native video playback</strong><span>Use Video mode freely. Choose an analysis mode only when you want ParFolio to load the AI tools.</span>'});
 e.querySelectorAll('[data-phase]').forEach(b=>b.onclick=()=>{if(!S.swing)return;S.swing.marks[b.dataset.phase]=v.currentTime;status.textContent=`${b.dataset.phase} marked at ${v.currentTime.toFixed(2)}s`});
 e.querySelectorAll('[data-mode]').forEach(b=>b.onclick=async()=>{S.mode=b.dataset.mode;e.querySelectorAll('[data-mode]').forEach(q=>q.classList.toggle('active',q===b));setCanvasMode();if(S.mode==='video'){help.textContent='Video mode. Native playback only; all analysis engines remain idle.';panel.innerHTML='<strong>Native video playback</strong><span>AI analysis is off.</span>';return}if(S.mode==='plane'){help.textContent='Tap two points to set a swing-plane reference line. No AI model is required.';panel.innerHTML='<strong>Swing plane</strong><span>Tap two reference points on the video.</span>';drawSwing(c,v);return}if(!S.swing){status.textContent='Choose a swing video before starting analysis.';return}status.textContent='Loading analysis tools…';panel.innerHTML='<strong>Loading analysis</strong><span>ParFolio is loading only the tools needed for swing analysis.</span>';try{await loadSwingModules();if(window.ParFolioPoseTrace)window.ParFolioPoseTrace.start();if(window.ParFolioHandPath)window.ParFolioHandPath.reset();if(window.ParFolioClubTrack)window.ParFolioClubTrack.reset();if(window.ParFolioSwingPhases)window.ParFolioSwingPhases.reset();help.textContent=S.mode==='skeleton'?'Automatic golf pose trace.':S.mode==='path'?'Estimated Club Path preview.':S.mode==='analytics'?'Validated 2D pose analytics.':'AI Coach uses validated measurements only.';status.textContent='Analysis tools ready. Press Play or scrub the video.'}catch(err){console.error('ParFolio lazy analysis load:',err);status.textContent='Analysis tools could not load on this device.'}});
 c.onclick=ev=>{if(!S.swing||S.mode!=='plane')return;const p=pt(ev,c);if(S.plane.length>=2)S.plane=[];S.plane.push(p);drawSwing(c,v)};
 e.querySelector('#pf-ai-overlay-clear').onclick=()=>{S.plane=[];drawSwing(c,v);status.textContent='Swing overlays cleared.'};e.querySelector('#pf-ai-swing-save').onclick=()=>status.textContent='Swing draft saved for this preview session.';setCanvasMode();return true};
 function drawTracer(c,v,points){const x=c.getContext('2d'),[w,h]=canvasSize(c,v);x.clearRect(0,0,w,h);if(!points.length)return;x.lineWidth=Math.max(4,w*.012);x.lineCap='round';x.strokeStyle='#f0cb5b';x.shadowColor='rgba(240,203,91,.75)';x.shadowBlur=10;x.beginPath();x.moveTo(points[0].x*w,points[0].y*h);if(points.length===3)x.quadraticCurveTo(points[1].x*w,points[1].y*h,points[2].x*w,points[2].y*h);else points.slice(1).forEach(p=>x.lineTo(p.x*w,p.y*h));x.stroke();x.shadowBlur=0}
 window.openShotVision=function(){if(!access())return false;const e=shell('Shot Vision','Create and refine a ball-flight tracer.',`${picker('shot')}<div id="pf-ai-shot-editor" class="pf-ai-editor" hidden><div class="pf-ai-video-wrap"><video id="pf-ai-shot-video" controls playsinline preload="metadata"></video><canvas id="pf-ai-shot-canvas"></canvas></div><div class="pf-ai-instructions">Choose a video first. Automatic tracking loads only after the video is selected.</div><div class="pf-ai-actions"><button id="pf-ai-shot-clear">Clear</button><button id="pf-ai-shot-save" class="pf-ai-primary">Save tracer draft</button></div><div id="pf-ai-shot-status" class="pf-ai-status">Choose or record a shot video.</div></div>`);const ed=e.querySelector('#pf-ai-shot-editor'),v=e.querySelector('#pf-ai-shot-video'),c=e.querySelector('#pf-ai-shot-canvas'),st=e.querySelector('#pf-ai-shot-status');bindVideoSources(e,'shot',async f=>{if(S.shot?.url)URL.revokeObjectURL(S.shot.url);S.shot={file:f,url:URL.createObjectURL(f),points:[]};v.src=S.shot.url;v.preload='metadata';ed.hidden=false;st.textContent='Video ready. Loading Shot Vision tracer…';try{await loadShotModule();if(window.ParFolioShotVision){window.ParFolioShotVision.reset();window.ParFolioShotVision.start()}st.textContent='Shot Vision ready. Press Play.'}catch(err){console.error('ParFolio Shot Vision lazy load:',err);st.textContent='Shot Vision could not load on this device.'}});c.onclick=ev=>{if(!S.shot||window.ParFolioShotVision)return;if(S.shot.points.length>=3)S.shot.points=[];S.shot.points.push(pt(ev,c));drawTracer(c,v,S.shot.points);st.textContent=S.shot.points.length===3?'Tracer ready.':'Add the next tracer point.'};e.querySelector('#pf-ai-shot-clear').onclick=()=>{S.shot&&(S.shot.points=[]);if(window.ParFolioShotVision)window.ParFolioShotVision.reset();else drawTracer(c,v,[])};e.querySelector('#pf-ai-shot-save').onclick=()=>{if(window.ParFolioShotVision?.hasTrack?.())st.textContent='Automatic tracer draft saved for this preview session.';else st.textContent=S.shot?.points?.length===3?'Tracer draft saved for this preview session.':'Play the shot or add tracer points first.'};return true};
 function menu(){document.querySelectorAll('.app-side-menu.menu-v204').forEach(m=>{if(!access()){m.querySelectorAll('[data-parfolio-ai-menu]').forEach(n=>n.remove());close();return}if(m.querySelector('[data-parfolio-ai-menu]'))return;const settings=[...m.querySelectorAll('.menu-section-label')].find(x=>/SETTINGS|AJUSTES|设置|PENGATURAN|सेटिंग्स|RÉGLAGES/i.test(x.textContent)),l=document.createElement('div'),b=document.createElement('button');l.className='menu-section-label';l.dataset.parfolioAiMenu='1';l.textContent='PARFOLIO AI';b.className='pf-ai-menu-button';b.dataset.parfolioAiMenu='1';b.innerHTML='<span class="menu-line-icon">✦</span><div>Swing AI + Shot Vision<small>Admin preview</small></div>';b.onclick=()=>{if(typeof closeRoundQuickMenu==='function')closeRoundQuickMenu();openParFolioAI()};if(settings){m.insertBefore(l,settings);m.insertBefore(b,settings)}else{m.append(l,b)}})}
 new MutationObserver(menu).observe(document.body,{childList:true,subtree:true});menu();window.ParFolioAI={open:window.openParFolioAI,openSwing:window.openSwingAI,openShot:window.openShotVision,hasAccess:access,version:245};
})();