/* ParFolio v211 — DM photos + delete controls. Loaded after social-v208. */
(function(){
  const dbx=()=>typeof db!=='undefined'?db:null;
  const uid=()=>typeof currentUser!=='undefined'&&currentUser?.id?currentUser.id:null;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let timer=null;
  const signedCache=new Map();
  function close(){clearInterval(timer);timer=null;document.querySelector('.pf-social-overlay')?.remove()}
  async function profile(userId){const {data}=await dbx().from('social_profiles').select('display_name,avatar_path').eq('user_id',userId).maybeSingle();return data||{display_name:'Golfer'}}
  function avatar(p){const name=p?.display_name||'Golfer';let url='';try{if(p?.avatar_path)url=dbx().storage.from('golfer-avatars').getPublicUrl(p.avatar_path).data.publicUrl}catch{}return `<span class="pf-social-avatar">${url?`<img src="${esc(url)}" alt="">`:esc((name[0]||'G').toUpperCase())}</span>`}
  async function signed(path){if(!path)return'';if(signedCache.has(path)&&signedCache.get(path).expires>Date.now())return signedCache.get(path).url;const {data,error}=await dbx().storage.from('dm-media').createSignedUrl(path,3600);if(error)return'';signedCache.set(path,{url:data.signedUrl,expires:Date.now()+3300000});return data.signedUrl}
  async function shrinkImage(file){if(!file?.type?.startsWith('image/'))throw new Error('Please choose a photo. Video uploads are not enabled.');if(file.size>20*1024*1024)throw new Error('That photo is too large. Choose an image under 20 MB.');const url=URL.createObjectURL(file);try{const img=await new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=()=>rej(new Error('This photo format could not be opened.'));i.src=url});const max=1600,scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight)),w=Math.max(1,Math.round(img.naturalWidth*scale)),h=Math.max(1,Math.round(img.naturalHeight*scale));const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(img,0,0,w,h);const blob=await new Promise((res,rej)=>canvas.toBlob(b=>b?res(b):rej(new Error('Could not prepare this photo.')),'image/jpeg',.84));if(blob.size>8*1024*1024)throw new Error('Photo is still too large after compression.');return blob}finally{URL.revokeObjectURL(url)}}
  function shell(name,p){close();const o=document.createElement('div');o.className='pf-social-overlay';o.innerHTML=`<section class="pf-social-shell"><header class="pf-social-head"><button type="button" data-close>‹</button><div><b>Direct Message</b><small>Private friend conversation</small></div></header><div class="pf-social-thread"><div class="pf-social-peer">${avatar(p)}<div><b>${esc(name)}</b><small>ParFolio friend</small></div></div><div id="pfThreadList" class="pf-social-thread-list"></div><form class="pf-social-compose pf-social-compose-v211" id="pfDmForm"><input type="file" id="pfDmPhoto" accept="image/jpeg,image/png,image/webp,image/*" hidden><button type="button" class="pf-social-photo-btn" id="pfDmPhotoBtn" aria-label="Send photo">Photo</button><textarea id="pfDmBody" maxlength="2000" placeholder="Message ${esc(name)}"></textarea><button type="submit">Send</button></form></div></section>`;document.body.appendChild(o);o.querySelector('[data-close]').onclick=close;return o}
  async function rows(cid){const {data,error}=await dbx().from('direct_messages').select('id,sender_id,body,image_path,created_at,read_at,deleted_at').eq('conversation_id',cid).order('created_at',{ascending:true}).limit(250);if(error)throw error;return data||[]}
  async function render(cid,host){const me=uid(),list=await rows(cid),nearBottom=host.scrollHeight-host.scrollTop-host.clientHeight<100;const html=[];for(const m of list){const mine=m.sender_id===me;if(m.deleted_at){html.push(`<div class="pf-social-bubble ${mine?'mine':''} pf-social-deleted">Message deleted<small>${new Date(m.created_at).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</small></div>`);continue}let image='';if(m.image_path){const url=await signed(m.image_path);if(url)image=`<button class="pf-dm-image" type="button" onclick="openParFolioDmPhoto('${esc(url)}')"><img src="${esc(url)}" alt="Shared photo"></button>`}const action=mine?`<button class="pf-dm-more" onclick="deleteParFolioDmEveryone(${m.id})" title="Delete for everyone">•••</button>`:`<button class="pf-dm-more" onclick="deleteParFolioDmForMe(${m.id})" title="Delete for me">•••</button>`;html.push(`<div class="pf-social-bubble ${mine?'mine':''}" data-message-id="${m.id}">${action}${image}${m.body?`<div class="pf-dm-text">${esc(m.body)}</div>`:''}<small>${new Date(m.created_at).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</small></div>`)}host.innerHTML=html.join('')||'<div class="pf-social-empty">Say hello</div>';if(nearBottom)host.scrollTop=host.scrollHeight;await dbx().rpc('social_mark_dm_read',{conversation:cid})}
  window.openParFolioDmPhoto=function(url){const o=document.createElement('div');o.className='pf-dm-photo-viewer';o.innerHTML=`<button aria-label="Close">×</button><img src="${esc(url)}" alt="Shared photo">`;document.body.appendChild(o);o.onclick=e=>{if(e.target===o||e.target.tagName==='BUTTON')o.remove()}}
  window.deleteParFolioDmForMe=async function(id){if(!confirm('Delete this message from your view?'))return;const {error}=await dbx().rpc('social_delete_dm_for_me',{message_id:id});if(error)return alert(error.message);document.querySelector(`[data-message-id="${id}"]`)?.remove()}
  window.deleteParFolioDmEveryone=async function(id){if(!confirm('Delete this message for everyone?'))return;const {data:path,error}=await dbx().rpc('social_delete_dm_for_everyone',{message_id:id});if(error)return alert(error.message);if(path){try{await dbx().storage.from('dm-media').remove([path])}catch{}}document.querySelector(`[data-message-id="${id}"]`)?.replaceWith(Object.assign(document.createElement('div'),{className:'pf-social-bubble mine pf-social-deleted',textContent:'Message deleted'}))}
  window.openSocialThread=async function(conversationId,targetUser){if(!uid()||!dbx())return;const p=await profile(targetUser),name=p.display_name||'Golfer',overlay=shell(name,p),host=overlay.querySelector('#pfThreadList'),form=overlay.querySelector('#pfDmForm'),box=overlay.querySelector('#pfDmBody'),file=overlay.querySelector('#pfDmPhoto'),photoBtn=overlay.querySelector('#pfDmPhotoBtn');const load=async()=>{try{await render(conversationId,host)}catch(e){host.innerHTML=`<div class="pf-social-error">${esc(e.message||e)}</div>`}};await load();form.onsubmit=async e=>{e.preventDefault();const body=box.value.trim();if(!body)return;box.disabled=true;const {error}=await dbx().rpc('social_send_dm',{conversation:conversationId,message_body:body});box.disabled=false;if(error)return alert(error.message);box.value='';await load()};photoBtn.onclick=()=>file.click();file.onchange=async()=>{const chosen=file.files?.[0];file.value='';if(!chosen)return;photoBtn.disabled=true;photoBtn.textContent='Sending…';try{const blob=await shrinkImage(chosen),path=`${conversationId}/${uid()}/${crypto.randomUUID()}.jpg`,up=await dbx().storage.from('dm-media').upload(path,blob,{contentType:'image/jpeg',upsert:false});if(up.error)throw up.error;const caption=box.value.trim(),sent=await dbx().rpc('social_send_dm_photo',{conversation:conversationId,storage_path:path,caption});if(sent.error){await dbx().storage.from('dm-media').remove([path]);throw sent.error}box.value='';await load()}catch(e){alert(e.message||e)}finally{photoBtn.disabled=false;photoBtn.textContent='Photo'}};timer=setInterval(load,5000)};
})();