/* ParFolio v208 — Friends + persistent 1:1 direct messages. Round Chat remains separate. */
(function(){
  let unreadDm=0,socialTimer=null,threadTimer=null;
  const escSocial=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const uid=()=>typeof currentUser!=='undefined'&&currentUser?.id?currentUser.id:null;
  const dbx=()=>typeof db!=='undefined'?db:null;
  const profileName=()=>{const p=typeof golferProfile!=='undefined'?golferProfile:null,u=typeof currentUser!=='undefined'?currentUser:null;return [p?.first_name,p?.last_name].filter(Boolean).join(' ').trim()||u?.user_metadata?.full_name||u?.user_metadata?.name||u?.email?.split('@')[0]||'Golfer'};
  const profileAvatar=()=>typeof golferProfile!=='undefined'?golferProfile?.avatar_path||null:null;
  function avatarUrlSocial(path){try{return path?dbx().storage.from('golfer-avatars').getPublicUrl(path).data.publicUrl:''}catch{return''}}
  function avatarMarkupSocial(p){const name=p?.display_name||'Golfer',url=avatarUrlSocial(p?.avatar_path);return `<span class="pf-social-avatar">${url?`<img src="${escSocial(url)}" alt="">`:escSocial((name[0]||'G').toUpperCase())}</span>`}
  async function socialReady(){if(!uid()||!dbx())return false;try{const {error}=await dbx().from('social_profiles').upsert({user_id:uid(),display_name:profileName().slice(0,80),avatar_path:profileAvatar(),updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)throw error;return true}catch(e){console.warn('ParFolio social unavailable:',e?.message||e);return false}}
  async function profileMap(ids){const unique=[...new Set(ids.filter(Boolean))];if(!unique.length)return new Map();const {data}=await dbx().from('social_profiles').select('user_id,display_name,avatar_path').in('user_id',unique);return new Map((data||[]).map(p=>[p.user_id,p]))}
  function closeSocial(){clearInterval(threadTimer);threadTimer=null;document.querySelector('.pf-social-overlay')?.remove()}
  function shell(title,subtitle='Friends & Messages'){closeSocial();const o=document.createElement('div');o.className='pf-social-overlay';o.innerHTML=`<section class="pf-social-shell"><header class="pf-social-head"><button type="button" data-close>‹</button><div><b>${escSocial(title)}</b><small>${escSocial(subtitle)}</small></div></header><div id="pfSocialRoot" class="pf-social-body"></div></section>`;document.body.appendChild(o);o.querySelector('[data-close]').onclick=closeSocial;return o.querySelector('#pfSocialRoot')}
  function tabs(active){return `<nav class="pf-social-tabs"><button class="${active==='messages'?'on':''}" onclick="openParFolioSocial('messages')">Messages${unreadDm?` <span class="pf-social-count">${unreadDm>99?'99+':unreadDm}</span>`:''}</button><button class="${active==='friends'?'on':''}" onclick="openParFolioSocial('friends')">Friends</button></nav>`}
  window.openParFolioSocial=async function(tab='messages'){if(!uid()){alert('Please sign in to use Friends and Messages.');return}const root=shell(tab==='friends'?'Friends':'Messages');root.parentElement.insertBefore(document.createRange().createContextualFragment(tabs(tab)),root);if(!(await socialReady())){root.innerHTML='<div class="pf-social-error">Friends & Messages are being enabled for this ParFolio release. Please try again after the database update is installed.</div>';return}if(tab==='friends')await renderFriends(root);else await renderMessages(root)};
  async function renderFriends(root){root.innerHTML=`<form class="pf-social-search" id="pfFriendSearch"><input id="pfFriendQuery" placeholder="Find golfers by name" autocomplete="off"><button>Search</button></form><div id="pfFriendContent"><div class="pf-social-empty">Loading friends…</div></div>`;root.querySelector('#pfFriendSearch').onsubmit=async e=>{e.preventDefault();await searchGolfers(root.querySelector('#pfFriendQuery').value,root.querySelector('#pfFriendContent'))};await loadFriendsHome(root.querySelector('#pfFriendContent'))}
  async function loadFriendsHome(host){const me=uid();const [{data:requests},{data:friends}]=await Promise.all([dbx().from('friend_requests').select('id,sender_id,receiver_id,status,created_at').eq('receiver_id',me).eq('status','pending').order('created_at',{ascending:false}),dbx().from('friendships').select('user_a,user_b,created_at').or(`user_a.eq.${me},user_b.eq.${me}`).order('created_at',{ascending:false})]);const incoming=requests||[],rows=friends||[],ids=[...incoming.map(r=>r.sender_id),...rows.map(f=>f.user_a===me?f.user_b:f.user_a)],profiles=await profileMap(ids);host.innerHTML=`${incoming.length?`<section class="pf-social-section"><h3>FRIEND REQUESTS</h3>${incoming.map(r=>{const p=profiles.get(r.sender_id)||{display_name:'Golfer'};return `<article class="pf-social-card">${avatarMarkupSocial(p)}<div class="pf-social-card-copy"><b>${escSocial(p.display_name)}</b><small>Wants to add you as a friend</small></div><div class="pf-social-actions"><button class="pf-social-action" onclick="socialRespondFriend('${r.id}',true)">Accept</button><button class="pf-social-action secondary" onclick="socialRespondFriend('${r.id}',false)">Decline</button></div></article>`}).join('')}</section>`:''}<section class="pf-social-section"><h3>MY FRIENDS</h3>${rows.length?rows.map(f=>{const other=f.user_a===me?f.user_b:f.user_a,p=profiles.get(other)||{display_name:'Golfer'};return `<article class="pf-social-card">${avatarMarkupSocial(p)}<div class="pf-social-card-copy"><b>${escSocial(p.display_name)}</b><small>ParFolio friend</small></div><div class="pf-social-actions"><button class="pf-social-action" onclick="socialMessageFriend('${other}')">Message</button><button class="pf-social-action secondary" onclick="socialRemoveFriend('${other}')">Remove</button></div></article>`}).join(''):'<div class="pf-social-empty">No friends yet. Search for a golfer above.</div>'}</section>`}
  async function searchGolfers(q,host){q=String(q||'').trim();if(q.length<2){host.innerHTML='<div class="pf-social-empty">Enter at least 2 letters.</div>';return}const me=uid(),{data,error}=await dbx().from('social_profiles').select('user_id,display_name,avatar_path').ilike('display_name',`%${q.replace(/[%_]/g,'')}%`).neq('user_id',me).order('display_name').limit(30);if(error){host.innerHTML=`<div class="pf-social-error">${escSocial(error.message)}</div>`;return}const ids=(data||[]).map(p=>p.user_id);let friends=[];if(ids.length){const {data:f}=await dbx().from('friendships').select('user_a,user_b').or(`user_a.eq.${me},user_b.eq.${me}`);friends=f||[]}const friendSet=new Set(friends.map(f=>f.user_a===me?f.user_b:f.user_a));host.innerHTML=`<section class="pf-social-section"><h3>SEARCH RESULTS</h3>${(data||[]).length?(data||[]).map(p=>`<article class="pf-social-card">${avatarMarkupSocial(p)}<div class="pf-social-card-copy"><b>${escSocial(p.display_name)}</b><small>${friendSet.has(p.user_id)?'Friend':'ParFolio golfer'}</small></div><div class="pf-social-actions">${friendSet.has(p.user_id)?`<button class="pf-social-action" onclick="socialMessageFriend('${p.user_id}')">Message</button>`:`<button class="pf-social-action" onclick="socialAddFriend('${p.user_id}',this)">Add Friend</button>`}</div></article>`).join(''):'<div class="pf-social-empty">No golfers found yet. Golfer profiles become discoverable after they open the updated ParFolio app.</div>'}</section>`}
  window.socialAddFriend=async function(target,button){button&&(button.disabled=true);const {error}=await dbx().rpc('social_send_friend_request',{target_user:target});if(error){alert(error.message);button&&(button.disabled=false);return}if(button)button.textContent='Request Sent'};
  window.socialRespondFriend=async function(id,accept){const {error}=await dbx().rpc('social_respond_friend_request',{request_id:id,accept_request:accept});if(error)return alert(error.message);openParFolioSocial('friends')};
  window.socialRemoveFriend=async function(target){if(!confirm('Remove this golfer from your friends?'))return;const {error}=await dbx().rpc('social_remove_friend',{target_user:target});if(error)return alert(error.message);openParFolioSocial('friends')};
  window.socialMessageFriend=async function(target){const {data,error}=await dbx().rpc('social_open_dm',{target_user:target});if(error)return alert(error.message);openSocialThread(data,target)};
  async function renderMessages(root){root.innerHTML='<div class="pf-social-empty">Loading conversations…</div>';const me=uid(),{data,error}=await dbx().from('direct_conversations').select('id,user_a,user_b,last_message_at').or(`user_a.eq.${me},user_b.eq.${me}`).order('last_message_at',{ascending:false});if(error){root.innerHTML=`<div class="pf-social-error">${escSocial(error.message)}</div>`;return}const conversations=data||[],others=conversations.map(c=>c.user_a===me?c.user_b:c.user_a),profiles=await profileMap(others),ids=conversations.map(c=>c.id);let messages=[];if(ids.length){const r=await dbx().from('direct_messages').select('id,conversation_id,sender_id,body,created_at,read_at').in('conversation_id',ids).order('created_at',{ascending:false});messages=r.data||[]}const last=new Map();for(const m of messages)if(!last.has(m.conversation_id))last.set(m.conversation_id,m);root.innerHTML=`${conversations.length?conversations.map(c=>{const other=c.user_a===me?c.user_b:c.user_a,p=profiles.get(other)||{display_name:'Golfer'},m=last.get(c.id),unread=m&&m.sender_id!==me&&!m.read_at;return `<article class="pf-social-card pf-social-conversation ${unread?'unread':''}" onclick="openSocialThread('${c.id}','${other}')">${avatarMarkupSocial(p)}<div class="pf-social-card-copy"><b>${escSocial(p.display_name)}</b><small>${m?escSocial(m.body):'Start a conversation'}</small></div>${unread?'<span class="pf-social-count">New</span>':''}</article>`}).join(''):'<div class="pf-social-empty">No direct messages yet.<br>Open Friends to add someone and start a conversation.</div>'}`}
  window.openSocialThread=async function(conversationId,targetUser){clearInterval(threadTimer);const root=shell('Direct Message','Private friend conversation'),profiles=await profileMap([targetUser]),p=profiles.get(targetUser)||{display_name:'Golfer'};root.className='pf-social-thread';root.innerHTML=`<div class="pf-social-head" style="border-radius:0"><span>${avatarMarkupSocial(p)}</span><div><b>${escSocial(p.display_name)}</b><small>ParFolio friend</small></div></div><div id="pfThreadList" class="pf-social-thread-list"></div><form class="pf-social-compose" id="pfDmForm"><textarea id="pfDmBody" maxlength="2000" placeholder="Message ${escSocial(p.display_name)}"></textarea><button>Send</button></form>`;const load=()=>loadThread(conversationId,root.querySelector('#pfThreadList'));await load();await dbx().rpc('social_mark_dm_read',{conversation:conversationId});updateUnread();root.querySelector('#pfDmForm').onsubmit=async e=>{e.preventDefault();const box=root.querySelector('#pfDmBody'),body=box.value.trim();if(!body)return;box.disabled=true;const {error}=await dbx().rpc('social_send_dm',{conversation:conversationId,message_body:body});box.disabled=false;if(error)return alert(error.message);box.value='';await load()};threadTimer=setInterval(load,5000)};
  async function loadThread(cid,host){const me=uid(),{data,error}=await dbx().from('direct_messages').select('id,sender_id,body,created_at,read_at').eq('conversation_id',cid).order('created_at',{ascending:true}).limit(250);if(error){host.innerHTML=`<div class="pf-social-error">${escSocial(error.message)}</div>`;return}const wasBottom=host.scrollHeight-host.scrollTop-host.clientHeight<90;host.innerHTML=(data||[]).map(m=>`<div class="pf-social-bubble ${m.sender_id===me?'mine':''}">${escSocial(m.body)}<small>${new Date(m.created_at).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</small></div>`).join('')||'<div class="pf-social-empty">Say hello 👋</div>';if(wasBottom)host.scrollTop=host.scrollHeight;await dbx().rpc('social_mark_dm_read',{conversation:cid});updateUnread()}
  async function updateUnread(){if(!uid()||!dbx()){unreadDm=0;decorateMenu();return}try{const {data}=await dbx().rpc('social_unread_dm_count');unreadDm=Number(data)||0;decorateMenu()}catch{}}
  function decorateMenu(){const menu=document.querySelector('.app-side-menu');if(!menu)return;menu.querySelector('.pf-social-menu-section')?.remove();const golf=[...menu.querySelectorAll('.menu-section-label')].find(x=>/GOLF|高尔夫|गोल्फ/i.test(x.textContent||'')),anchor=golf||menu.querySelector('.menu-start-round');if(!anchor)return;const frag=document.createRange().createContextualFragment(`<div class="menu-section-label pf-social-menu-section">SOCIAL</div><button class="pf-social-menu-section" onclick="closeRoundQuickMenu();openParFolioSocial('messages')"><span class="menu-line-icon">✉</span><div>Messages</div>${unreadDm?`<span class="pf-social-menu-badge">${unreadDm>99?'99+':unreadDm}</span>`:''}</button><button class="pf-social-menu-section" onclick="closeRoundQuickMenu();openParFolioSocial('friends')"><span class="menu-line-icon">◎</span><div>Friends</div></button>`);anchor.parentNode.insertBefore(frag,anchor)}
  const priorMenu=typeof showAppMenu==='function'?showAppMenu:null;if(priorMenu)showAppMenu=function(){priorMenu.apply(this,arguments);setTimeout(decorateMenu,0)};
  async function bootSocial(){if(await socialReady())updateUnread();clearInterval(socialTimer);socialTimer=setInterval(updateUnread,30000)}
  setTimeout(bootSocial,1800);setTimeout(bootSocial,5000);
})();