-- ParFolio v207: privacy-safe social profiles, friends, blocking and direct messages.
-- Existing private golfer contact data is not exposed by this feature.

create extension if not exists pgcrypto;

create table if not exists public.social_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 80),
  avatar_path text,
  updated_at timestamptz not null default now()
);

create table if not exists public.friend_requests (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid not null references auth.users(id) on delete cascade,
  receiver_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted','declined','cancelled')),
  created_at timestamptz not null default now(),
  responded_at timestamptz,
  check (sender_id <> receiver_id)
);
create unique index if not exists friend_requests_pending_pair_idx
  on public.friend_requests (least(sender_id,receiver_id), greatest(sender_id,receiver_id))
  where status='pending';
create index if not exists friend_requests_receiver_idx on public.friend_requests(receiver_id,status,created_at desc);
create index if not exists friend_requests_sender_idx on public.friend_requests(sender_id,status,created_at desc);

create table if not exists public.friendships (
  user_a uuid not null references auth.users(id) on delete cascade,
  user_b uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_a,user_b),
  check (user_a < user_b)
);
create index if not exists friendships_user_b_idx on public.friendships(user_b);

create table if not exists public.user_blocks (
  blocker_id uuid not null references auth.users(id) on delete cascade,
  blocked_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id,blocked_id),
  check (blocker_id <> blocked_id)
);

create table if not exists public.direct_conversations (
  id uuid primary key default gen_random_uuid(),
  user_a uuid not null references auth.users(id) on delete cascade,
  user_b uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  last_message_at timestamptz not null default now(),
  check (user_a < user_b),
  unique (user_a,user_b)
);
create index if not exists direct_conversations_user_a_idx on public.direct_conversations(user_a,last_message_at desc);
create index if not exists direct_conversations_user_b_idx on public.direct_conversations(user_b,last_message_at desc);

create table if not exists public.direct_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.direct_conversations(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(btrim(body)) between 1 and 2000),
  created_at timestamptz not null default now(),
  read_at timestamptz
);
create index if not exists direct_messages_conversation_idx on public.direct_messages(conversation_id,created_at);
create index if not exists direct_messages_unread_idx on public.direct_messages(conversation_id,read_at) where read_at is null;

alter table public.social_profiles enable row level security;
alter table public.friend_requests enable row level security;
alter table public.friendships enable row level security;
alter table public.user_blocks enable row level security;
alter table public.direct_conversations enable row level security;
alter table public.direct_messages enable row level security;

-- Public social profile = display name + avatar only. Contact information remains elsewhere/private.
drop policy if exists social_profiles_authenticated_read on public.social_profiles;
create policy social_profiles_authenticated_read on public.social_profiles for select to authenticated using (true);
drop policy if exists social_profiles_own_insert on public.social_profiles;
create policy social_profiles_own_insert on public.social_profiles for insert to authenticated with check (user_id=auth.uid());
drop policy if exists social_profiles_own_update on public.social_profiles;
create policy social_profiles_own_update on public.social_profiles for update to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());

drop policy if exists friend_requests_participant_read on public.friend_requests;
create policy friend_requests_participant_read on public.friend_requests for select to authenticated using (auth.uid() in (sender_id,receiver_id));
drop policy if exists friend_requests_sender_insert on public.friend_requests;
create policy friend_requests_sender_insert on public.friend_requests for insert to authenticated with check (sender_id=auth.uid());

drop policy if exists friendships_participant_read on public.friendships;
create policy friendships_participant_read on public.friendships for select to authenticated using (auth.uid() in (user_a,user_b));

drop policy if exists user_blocks_own_all on public.user_blocks;
create policy user_blocks_own_all on public.user_blocks for all to authenticated using (blocker_id=auth.uid()) with check (blocker_id=auth.uid());

drop policy if exists direct_conversations_participant_read on public.direct_conversations;
create policy direct_conversations_participant_read on public.direct_conversations for select to authenticated using (auth.uid() in (user_a,user_b));

drop policy if exists direct_messages_participant_read on public.direct_messages;
create policy direct_messages_participant_read on public.direct_messages for select to authenticated using (
  exists (select 1 from public.direct_conversations c where c.id=conversation_id and auth.uid() in (c.user_a,c.user_b))
);
drop policy if exists direct_messages_participant_insert on public.direct_messages;
create policy direct_messages_participant_insert on public.direct_messages for insert to authenticated with check (
  sender_id=auth.uid() and exists (select 1 from public.direct_conversations c where c.id=conversation_id and auth.uid() in (c.user_a,c.user_b))
);

create or replace function public.social_send_friend_request(target_user uuid)
returns uuid language plpgsql security definer
set search_path=pg_catalog,public,auth
as $$
declare me uuid:=auth.uid(); rid uuid;
begin
  if me is null or target_user is null or me=target_user then raise exception 'Invalid friend request'; end if;
  if exists(select 1 from public.user_blocks b where (b.blocker_id=me and b.blocked_id=target_user) or (b.blocker_id=target_user and b.blocked_id=me)) then raise exception 'Friend request unavailable'; end if;
  if exists(select 1 from public.friendships f where f.user_a=least(me,target_user) and f.user_b=greatest(me,target_user)) then raise exception 'Already friends'; end if;
  select id into rid from public.friend_requests r where r.status='pending' and least(r.sender_id,r.receiver_id)=least(me,target_user) and greatest(r.sender_id,r.receiver_id)=greatest(me,target_user) limit 1;
  if rid is not null then return rid; end if;
  insert into public.friend_requests(sender_id,receiver_id) values(me,target_user) returning id into rid;
  return rid;
end $$;

create or replace function public.social_respond_friend_request(request_id uuid, accept_request boolean)
returns boolean language plpgsql security definer
set search_path=pg_catalog,public,auth
as $$
declare me uuid:=auth.uid(); req public.friend_requests%rowtype;
begin
  select * into req from public.friend_requests where id=request_id and status='pending' for update;
  if req.id is null or req.receiver_id<>me then raise exception 'Request unavailable'; end if;
  if accept_request then
    if exists(select 1 from public.user_blocks b where (b.blocker_id=req.sender_id and b.blocked_id=req.receiver_id) or (b.blocker_id=req.receiver_id and b.blocked_id=req.sender_id)) then raise exception 'Friend request unavailable'; end if;
    insert into public.friendships(user_a,user_b) values(least(req.sender_id,req.receiver_id),greatest(req.sender_id,req.receiver_id)) on conflict do nothing;
    update public.friend_requests set status='accepted',responded_at=now() where id=req.id;
  else
    update public.friend_requests set status='declined',responded_at=now() where id=req.id;
  end if;
  return true;
end $$;

create or replace function public.social_remove_friend(target_user uuid)
returns boolean language plpgsql security definer
set search_path=pg_catalog,public,auth
as $$
declare me uuid:=auth.uid();
begin
  delete from public.friendships where user_a=least(me,target_user) and user_b=greatest(me,target_user);
  return true;
end $$;

create or replace function public.social_open_dm(target_user uuid)
returns uuid language plpgsql security definer
set search_path=pg_catalog,public,auth
as $$
declare me uuid:=auth.uid(); cid uuid; a uuid; b uuid;
begin
  if me is null or target_user is null or me=target_user then raise exception 'Invalid conversation'; end if;
  a:=least(me,target_user); b:=greatest(me,target_user);
  if not exists(select 1 from public.friendships f where f.user_a=a and f.user_b=b) then raise exception 'Direct messages are available between friends'; end if;
  if exists(select 1 from public.user_blocks x where (x.blocker_id=me and x.blocked_id=target_user) or (x.blocker_id=target_user and x.blocked_id=me)) then raise exception 'Conversation unavailable'; end if;
  insert into public.direct_conversations(user_a,user_b) values(a,b) on conflict(user_a,user_b) do update set user_a=excluded.user_a returning id into cid;
  return cid;
end $$;

create or replace function public.social_send_dm(conversation uuid, message_body text)
returns bigint language plpgsql security definer
set search_path=pg_catalog,public,auth
as $$
declare me uuid:=auth.uid(); mid bigint; other_user uuid;
begin
  if char_length(btrim(coalesce(message_body,''))) not between 1 and 2000 then raise exception 'Message must be 1-2000 characters'; end if;
  select case when c.user_a=me then c.user_b when c.user_b=me then c.user_a else null end into other_user from public.direct_conversations c where c.id=conversation;
  if other_user is null then raise exception 'Conversation unavailable'; end if;
  if exists(select 1 from public.user_blocks x where (x.blocker_id=me and x.blocked_id=other_user) or (x.blocker_id=other_user and x.blocked_id=me)) then raise exception 'Conversation unavailable'; end if;
  insert into public.direct_messages(conversation_id,sender_id,body) values(conversation,me,btrim(message_body)) returning id into mid;
  update public.direct_conversations set last_message_at=now() where id=conversation;
  return mid;
end $$;

create or replace function public.social_mark_dm_read(conversation uuid)
returns bigint language plpgsql security definer
set search_path=pg_catalog,public,auth
as $$
declare me uuid:=auth.uid(); n bigint;
begin
  if not exists(select 1 from public.direct_conversations c where c.id=conversation and me in (c.user_a,c.user_b)) then raise exception 'Conversation unavailable'; end if;
  update public.direct_messages set read_at=coalesce(read_at,now()) where conversation_id=conversation and sender_id<>me and read_at is null;
  get diagnostics n=row_count; return n;
end $$;

create or replace function public.social_unread_dm_count()
returns bigint language sql stable security definer
set search_path=pg_catalog,public,auth
as $$
  select count(*)::bigint from public.direct_messages m join public.direct_conversations c on c.id=m.conversation_id
  where auth.uid() in (c.user_a,c.user_b) and m.sender_id<>auth.uid() and m.read_at is null
$$;

grant execute on function public.social_send_friend_request(uuid) to authenticated;
grant execute on function public.social_respond_friend_request(uuid,boolean) to authenticated;
grant execute on function public.social_remove_friend(uuid) to authenticated;
grant execute on function public.social_open_dm(uuid) to authenticated;
grant execute on function public.social_send_dm(uuid,text) to authenticated;
grant execute on function public.social_mark_dm_read(uuid) to authenticated;
grant execute on function public.social_unread_dm_count() to authenticated;

revoke all on public.friend_requests from anon;
revoke all on public.friendships from anon;
revoke all on public.user_blocks from anon;
revoke all on public.direct_conversations from anon;
revoke all on public.direct_messages from anon;
